# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-25 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coolbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fbUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fbID', models.CharField(max_length=50)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('timeZone', models.CharField(max_length=50)),
                ('plainText', models.CharField(max_length=50)),
                ('locale', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'fbUser',
            },
        ),
    ]
