# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-25 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coolbot', '0003_remove_fbuser_plaintext'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbuser',
            name='preferLanguage',
            field=models.CharField(default='en', max_length=50),
        ),
    ]
