# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-25 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coolbot', '0004_fbuser_preferlanguage'),
    ]

    operations = [
        migrations.CreateModel(
            name='language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languageName', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'language',
            },
        ),
    ]
